## Creado/Editado por: HaJuegos Cat!. Si necesitas mas informacion, escribeme en Discord: https://discord.com/users/714622708649951272
## Created/Edited by: HaCatto! If you need more information, write me on Discord: https://discord.com/users/714622708649951272

execute as @e[type=ender_crystal] at @s run fill ~ ~50 ~ ~5 ~-50 ~50 bedrock replace obsidian
execute as @e[type=ender_crystal] at @s run fill ~ ~50 ~ ~-5 ~-50 ~-50 bedrock replace obsidian
execute as @e[type=ender_crystal] at @s run fill ~5 ~50 ~ ~5 ~-50 ~50 bedrock replace obsidian
execute as @e[type=ender_crystal] at @s run fill ~-5 ~50 ~ ~-5 ~-50 ~-50 bedrock replace obsidian
execute as @e[type=ender_crystal] at @s run fill ~ ~50 ~5 ~5 ~-50 ~50 bedrock replace obsidian
execute as @e[type=ender_crystal] at @s run fill ~ ~50 ~-5 ~-5 ~-50 ~-50 bedrock replace obsidian
execute as @e[type=ender_crystal] at @s run fill ~5 ~50 ~-5 ~ ~-50 ~ bedrock replace obsidian
execute as @e[type=ender_crystal] at @s run fill ~-5 ~50 ~5 ~ ~-50 ~ bedrock replace obsidian
execute as @e[type=ender_crystal] at @s positioned ~ ~-20 ~ run fill ~ ~50 ~ ~5 ~-50 ~50 bedrock replace obsidian
execute as @e[type=ender_crystal] at @s positioned ~ ~-20 ~ run fill ~ ~50 ~ ~-5 ~-50 ~-50 bedrock replace obsidian
execute as @e[type=ender_crystal] at @s positioned ~ ~-20 ~ run fill ~5 ~50 ~ ~5 ~-50 ~50 bedrock replace obsidian
execute as @e[type=ender_crystal] at @s positioned ~ ~-20 ~ run fill ~-5 ~50 ~ ~-5 ~-50 ~-50 bedrock replace obsidian
execute as @e[type=ender_crystal] at @s positioned ~ ~-20 ~ run fill ~ ~50 ~5 ~5 ~-50 ~50 bedrock replace obsidian
execute as @e[type=ender_crystal] at @s positioned ~ ~-20 ~ run fill ~ ~50 ~-5 ~-5 ~-50 ~-50 bedrock replace obsidian
execute as @e[type=ender_crystal] at @s positioned ~ ~-20 ~ run fill ~5 ~50 ~-5 ~ ~-50 ~ bedrock replace obsidian
execute as @e[type=ender_crystal] at @s positioned ~ ~-20 ~ run fill ~-5 ~50 ~5 ~ ~-50 ~ bedrock replace obsidian
execute as @e[type=ender_crystal] at @s positioned ~ ~-30 ~ run fill ~ ~50 ~ ~5 ~-50 ~50 bedrock replace obsidian
execute as @e[type=ender_crystal] at @s positioned ~ ~-30 ~ run fill ~ ~50 ~ ~-5 ~-50 ~-50 bedrock replace obsidian
execute as @e[type=ender_crystal] at @s positioned ~ ~-30 ~ run fill ~5 ~50 ~ ~5 ~-50 ~50 bedrock replace obsidian
execute as @e[type=ender_crystal] at @s positioned ~ ~-30 ~ run fill ~-5 ~50 ~ ~-5 ~-50 ~-50 bedrock replace obsidian
execute as @e[type=ender_crystal] at @s positioned ~ ~-30 ~ run fill ~ ~50 ~5 ~5 ~-50 ~50 bedrock replace obsidian
execute as @e[type=ender_crystal] at @s positioned ~ ~-30 ~ run fill ~ ~50 ~-5 ~-5 ~-50 ~-50 bedrock replace obsidian
execute as @e[type=ender_crystal] at @s positioned ~ ~-30 ~ run fill ~5 ~50 ~-5 ~ ~-50 ~ bedrock replace obsidian
execute as @e[type=ender_crystal] at @s positioned ~ ~-30 ~ run fill ~-5 ~50 ~5 ~ ~-50 ~ bedrock replace obsidian
execute as @e[type=ender_crystal] at @s positioned ~ ~-40 ~ run fill ~ ~50 ~ ~5 ~-50 ~50 bedrock replace obsidian
execute as @e[type=ender_crystal] at @s positioned ~ ~-40 ~ run fill ~ ~50 ~ ~-5 ~-50 ~-50 bedrock replace obsidian
execute as @e[type=ender_crystal] at @s positioned ~ ~-40 ~ run fill ~5 ~50 ~ ~5 ~-50 ~50 bedrock replace obsidian
execute as @e[type=ender_crystal] at @s positioned ~ ~-40 ~ run fill ~-5 ~50 ~ ~-5 ~-50 ~-50 bedrock replace obsidian
execute as @e[type=ender_crystal] at @s positioned ~ ~-40 ~ run fill ~ ~50 ~5 ~5 ~-50 ~50 bedrock replace obsidian
execute as @e[type=ender_crystal] at @s positioned ~ ~-40 ~ run fill ~ ~50 ~-5 ~-5 ~-50 ~-50 bedrock replace obsidian
execute as @e[type=ender_crystal] at @s positioned ~ ~-40 ~ run fill ~5 ~50 ~-5 ~ ~-50 ~ bedrock replace obsidian
execute as @e[type=ender_crystal] at @s positioned ~ ~-40 ~ run fill ~-5 ~50 ~5 ~ ~-50 ~ bedrock replace obsidian
execute as @e[type=ender_crystal] at @s positioned ~ ~-50 ~ run fill ~ ~50 ~ ~5 ~-50 ~50 bedrock replace obsidian
execute as @e[type=ender_crystal] at @s positioned ~ ~-50 ~ run fill ~ ~50 ~ ~-5 ~-50 ~-50 bedrock replace obsidian
execute as @e[type=ender_crystal] at @s positioned ~ ~-50 ~ run fill ~5 ~50 ~ ~5 ~-50 ~50 bedrock replace obsidian
execute as @e[type=ender_crystal] at @s positioned ~ ~-50 ~ run fill ~-5 ~50 ~ ~-5 ~-50 ~-50 bedrock replace obsidian
execute as @e[type=ender_crystal] at @s positioned ~ ~-50 ~ run fill ~ ~50 ~5 ~5 ~-50 ~50 bedrock replace obsidian
execute as @e[type=ender_crystal] at @s positioned ~ ~-50 ~ run fill ~ ~50 ~-5 ~-5 ~-50 ~-50 bedrock replace obsidian
execute as @e[type=ender_crystal] at @s positioned ~ ~-50 ~ run fill ~5 ~50 ~-5 ~ ~-50 ~ bedrock replace obsidian
execute as @e[type=ender_crystal] at @s positioned ~ ~-50 ~ run fill ~-5 ~50 ~5 ~ ~-50 ~ bedrock replace obsidian
execute as @e[type=ender_crystal] at @s positioned ~ ~-60 ~ run fill ~ ~50 ~ ~5 ~-50 ~50 bedrock replace obsidian
execute as @e[type=ender_crystal] at @s positioned ~ ~-60 ~ run fill ~ ~50 ~ ~-5 ~-50 ~-50 bedrock replace obsidian
execute as @e[type=ender_crystal] at @s positioned ~ ~-60 ~ run fill ~5 ~50 ~ ~5 ~-50 ~50 bedrock replace obsidian
execute as @e[type=ender_crystal] at @s positioned ~ ~-60 ~ run fill ~-5 ~50 ~ ~-5 ~-50 ~-50 bedrock replace obsidian
execute as @e[type=ender_crystal] at @s positioned ~ ~-60 ~ run fill ~ ~50 ~5 ~5 ~-50 ~50 bedrock replace obsidian
execute as @e[type=ender_crystal] at @s positioned ~ ~-60 ~ run fill ~ ~50 ~-5 ~-5 ~-50 ~-50 bedrock replace obsidian
execute as @e[type=ender_crystal] at @s positioned ~ ~-60 ~ run fill ~5 ~50 ~-5 ~ ~-50 ~ bedrock replace obsidian
execute as @e[type=ender_crystal] at @s positioned ~ ~-60 ~ run fill ~-5 ~50 ~5 ~ ~-50 ~ bedrock replace obsidian
execute as @e[type=ender_crystal] at @s positioned ~ ~-70 ~ run fill ~ ~50 ~ ~5 ~-50 ~50 bedrock replace obsidian
execute as @e[type=ender_crystal] at @s positioned ~ ~-70 ~ run fill ~ ~50 ~ ~-5 ~-50 ~-50 bedrock replace obsidian
execute as @e[type=ender_crystal] at @s positioned ~ ~-70 ~ run fill ~5 ~50 ~ ~5 ~-50 ~50 bedrock replace obsidian
execute as @e[type=ender_crystal] at @s positioned ~ ~-70 ~ run fill ~-5 ~50 ~ ~-5 ~-50 ~-50 bedrock replace obsidian
execute as @e[type=ender_crystal] at @s positioned ~ ~-70 ~ run fill ~ ~50 ~5 ~5 ~-50 ~50 bedrock replace obsidian
execute as @e[type=ender_crystal] at @s positioned ~ ~-70 ~ run fill ~ ~50 ~-5 ~-5 ~-50 ~-50 bedrock replace obsidian
execute as @e[type=ender_crystal] at @s positioned ~ ~-70 ~ run fill ~5 ~50 ~-5 ~ ~-50 ~ bedrock replace obsidian
execute as @e[type=ender_crystal] at @s positioned ~ ~-70 ~ run fill ~-5 ~50 ~5 ~ ~-50 ~ bedrock replace obsidian